name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  humble:
    uses: ubuntu-robotics/ros2-nav2-snap/.github/workflows/snap.yaml@humble
    with:
      branch-name: "humble"
  jazzy:
    uses: ubuntu-robotics/ros2-nav2-snap/.github/workflows/snap.yaml@jazzy
    with:
      branch-name: "jazzy"
